[package]
name = "webhook-bridge"
version = "0.0.0"

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0.33"
serde_json = "1.0.11"
rocket_contrib = "0.3.6"
serde_derive = "1.0.33"
hyper = "0.11.22"
futures = "0.1.18"
tokio-core = "0.1.15"
hyper-tls = "0.1.2"
num_cpus = "1.8.0"
