[global]
address = "0.0.0.0"
port = 8000
log = "normal"
secret_key = "EfQGXRA1bwv79+rmvBbEuavidgfBUDFsQDuNMz413JE="
limits = { forms = 32768 }

[development]
address = "localhost"

[production]
address = "0.0.0.0"
log = "critical"